src/Entity/Paste.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
/**
 * @ORM\Entity(repositoryClass="App\Repository\PasteRepository")
 * @ApiResource
 */
class Paste
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $content_type;

    public function getId()
    {
        return $this->id;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): self
    {
        $this->created = $created;

        return $this;
    }

    public function getContentType(): ?string
    {
        return $this->content_type;
    }

    public function setContentType(?string $content_type): self
    {
        $this->content_type = $content_type;

        return $this;
    }
}

src/Form/PasteType.php
<?php

namespace App\Form;

use App\Entity\Paste;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PasteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('content')
            ->add('created')
            ->add('content_type')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Paste::class,
        ]);
    }
}

src/Controller/PasteController.php
<?php

namespace App\Controller;

use App\Entity\Paste;
use App\Form\PasteType;
use App\Repository\PasteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/paste")
 */
class PasteController extends Controller
{
    /**
     * @Route("/", name="paste_index", methods="GET")
     */
    public function index(PasteRepository $pasteRepository): Response
    {
        return $this->render('paste/index.html.twig', ['pastes' => $pasteRepository->findAll()]);
    }

    /**
     * @Route("/new", name="paste_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $paste = new Paste();
        $form = $this->createForm(PasteType::class, $paste);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($paste);
            $em->flush();
            
            // Make sure message will be displayed after redirect
            $this->get('session')->getFlashBag()->add('message', 'paste bien ajouté');
            
            return $this->redirectToRoute('paste_index');
        }

        return $this->render('paste/new.html.twig', [
            'paste' => $paste,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="paste_show", methods="GET")
     */
    public function show(Paste $paste): Response
    {
        return $this->render('paste/show.html.twig', ['paste' => $paste]);
    }

    /**
     * @Route("/{id}/edit", name="paste_edit", methods="GET|POST")
     */
    public function edit(Request $request, Paste $paste): Response
    {
        $form = $this->createForm(PasteType::class, $paste);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();
            
            // Make sure message will be displayed after redirect
            $this->get('session')->getFlashBag()->add('message', 'paste bien modifié');
            
            return $this->redirectToRoute('paste_edit', ['id' => $paste->getId()]);
        }

        return $this->render('paste/edit.html.twig', [
            'paste' => $paste,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="paste_delete", methods="DELETE")
     */
    public function delete(Request $request, Paste $paste): Response
    {
        if ($this->isCsrfTokenValid('delete'.$paste->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($paste);
            $em->flush();
            
            // Make sure message will be displayed after redirect
            $this->get('session')->getFlashBag()->add('message', 'paste supprimé');
            
        }

        return $this->redirectToRoute('paste_index');
    }
}

templates/paste/_delete_form.html.twig
<form method="post" action="{{ path('paste_delete', {'id': paste.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ paste.id) }}">
    <button class="btn">Delete</button>
</form>

templates/paste/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/paste/edit.html.twig
{% extends 'baselayout.html.twig' %}

{% block title %}Edit Paste{% endblock %}

{% block main %}
    <h1>Edit Paste</h1>

    {{ include('paste/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('paste_index') }}">back to list</a>

    {{ include('paste/_delete_form.html.twig') }}
{% endblock %}

templates/paste/index.html.twig
{% extends 'baselayout.html.twig' %}

{% block title %}Paste index{% endblock %}

{% block main %}
    <h1>Paste index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Content</th>
                <th>Created</th>
                <th>Content_type</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for paste in pastes %}
            <tr>
                <td>{{ paste.id }}</td>
                <td>{{ paste.content }}</td>
                <td>{{ paste.created ? paste.created|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ paste.contentType }}</td>
                <td>
                    <a href="{{ path('paste_show', {'id': paste.id}) }}">show</a>
                    <a href="{{ path('paste_edit', {'id': paste.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('paste_new') }}">Create new</a>
{% endblock %}

templates/paste/new.html.twig
{% extends 'baselayout.html.twig' %}

{% block title %}New Paste{% endblock %}

{% block main %}
    <h1>Create new Paste</h1>

    {{ include('paste/_form.html.twig') }}

    <a href="{{ path('paste_index') }}">back to list</a>
{% endblock %}

templates/paste/show.html.twig
{% extends 'baselayout.html.twig' %}

{% block title %}Paste{% endblock %}

{% block main %}
    <h1>Paste</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ paste.id }}</td>
            </tr>
            <tr>
                <th>Content</th>
                <td>{{ paste.content }}</td>
            </tr>
            <tr>
                <th>Created</th>
                <td>{{ paste.created ? paste.created|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Content_type</th>
                <td>{{ paste.contentType }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('paste_index') }}">back to list</a>

    <a href="{{ path('paste_edit', {'id': paste.id}) }}">edit</a>

    {{ include('paste/_delete_form.html.twig') }}
{% endblock %}